name: data_gen
channels:
  - conda-forge
  - defaults
dependencies:
  - pip
  - appdirs=1.4.4
  - blas
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates
  - certifi=2023.7.22
  - cffi=1.15.1
  - charset-normalizer=2.0.4
  - contourpy=1.0.5
  - cryptography
  - cycler=0.11.0
  - cyrus-sasl
  - dbus
  - expat=2.5.0
  - fontconfig=2.14.1
  - fonttools
  - freetype=2.12.1
  - giflib=5.2.1
  - glib
  - gst-plugins-base
  - gstreamer
  - icu
  - idna=3.4
  - intel-openmp
  - jpeg
  - kiwisolver=1.4.4
  - krb5=1.20.1
  - lcms2
  - lerc
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libclang=14.0.6
  - libclang13=14.0.6
  - libdeflate
  - libedit
  - libevent
  - libffi
  - libgfortran5=11.3.0
  - libllvm14=14.0.6
  - libpng
  - libpq
  - libtiff
  - libuuid
  - libwebp
  - libwebp-base=1.2.4
  - libxcb
  - libxml2
  - libxslt=1.1.37
  - lz4-c=1.9.4
  - matplotlib=3.7.1
  - matplotlib-base=3.7.1
  - memory_profiler=0.58.0
  - mkl
  - mkl-service
  - mkl_fft
  - mkl_random
  - munkres=1.1.4
  - mysql=5.7.24
  - ncurses=6.4
  - nspr=4.35
  - nss=3.89.1
  - numpy
  - numpy-base
  - openssl=3.0.10
  - packaging=23.1
  - pcre=8.45
  - pillow
  - pip=23.2.1
  - ply=3.11
  - pooch=1.4.0
  - psutil=5.9.0
  - pycparser=2.21
  - pyopenssl=23.2.0
  - pyparsing=3.0.9
  - pyqt=5.15.7
  - pyqt5-sip=12.11.0
  - pysocks=1.7.1
  - python=
  - python-dateutil=2.8.2
  - qt-main
  - qt-webengine
  - qtwebkit
  - readline=8.2
  - requests=2.31.0
  - scipy=1.10.1
  - setuptools=68.0.0
  - sip=6.6.2
  - six=1.16.0
  - sqlite=3.41.2
  - tbb=2021.8.0
  - tk=8.6.12
  - toml=0.10.2
  - tornado=6.3.2
  - urllib3=1.26.16
  - wheel=0.38.4
  - xz=5.4.2
  - zlib=1.2.13
  - zstd=1.5.5

