name: build-and-push
on:
  workflow_dispatch:
  push:
    branches: [ "main", "ci-docker" ]
    paths:
      - "Dockerfile.pip"
      - "local_run/**"
      - ".github/workflows/build-and-push.yml"
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile.pip
          push: true
          tags: ghcr.io/arjhun-alt/pp-gwas-local:latest
          platforms: linux/amd64
          cache-from: type=gha
          cache-to: type=gha,mode=max
